### PR TITLE
Update Swiftlint and remove CocoaPods

### PR DESCRIPTION
**Pull request by vinnie4k**
## Overview

Updated Swiftlint package and removed CocoaPods.

### Swiftlint
- Swiftlint should now be installed via Homebrew: `brew install swiftlint`
  - Since Uplift uses mostly SPM, it doesn't make sense to use CocoaPods for just Swiftlint. Installing Swiftlint via SPM is possible, but there is currently a bug with SPM and Swiftlint involving OS incompatibility issues. You can read more about it [here](https://github.com/realm/SwiftLint/issues/5434).
  - As an alternative (actually the preferred way), we will be using Homebrew to install Swiftlint to avoid the SPM issue. To enforce Swiftlint, I rewrote the Swiftlint Build Script to echo an error message and exit with status code 1, which will cause the code to not build if Swiftlint is not installed on the device. See screenshot below.

### Other Changes

- Updated `README.md` with the new changes.
- Updated `ci_post_clone.sh` to remove CocoaPod installation and add Swiftlint installation.
- Fixed a small typo in `UpliftEnvironment.swift`.
- Updated environment variables with better naming to prepare for AppDev Ecosystem.
- Increased version to 2.5.2 and Build 9.

## Test Coverage

- Ran on both DEBUG and RELEASE schemes.
- Ensured that Swiftlint warning were still showing up. See screenshot below.
- Validated the bundled archive to ensure that it would upload properly to App Store Connect. Note that we may still experience Xcode Cloud issues.

## Next Steps
- Test the Xcode Cloud CI/CD configuration to make sure that changes to `ci_post_clone.sh` are correct. Note that there is also currently another issue regarding this that should be resolved.

### Swiftlint not installed
Screenshot 2024-03-14 at 1 38 59 AM

### Swiftlint installed
Screenshot 2024-03-14 at 1 37 44 AM

### CODE REVIEW

**Review by caitlynjin — APPROVED** [review]
Sounds good! What's the other issue you mentioned at the bottom?

**Comment by vinnie4k** [comment]
> Sounds good! What's the other issue you mentioned at the bottom?

There is an issue with Xcode Cloud that prevented the build from archiving successfully, but I believe I already resolved it. Not sure though.

**Comment by belle-hu** [comment]
I saw the earlier comment Caitlyn made and also the original PR mentioned a bug. How can I help test for this on my end?

**Comment by vinnie4k** [comment]
> I saw the earlier comment Caitlyn made and also the original PR mentioned a bug. How can I help test for this on my end?

No need to test. Once this PR gets merged, you will just need to make changes to your Xcode project.

**Pull request merged**
